{% set name = "python-markdown-math" %}
{% set version = "0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17a12175e8b2052a1c3402fca410841c551c678046293b1f7c280ccfe7b302a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - markdown >=3.0
    - python >=3.4

test:
  imports:
    - mdx_math
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mitya57/python-markdown-math
  summary: Math extension for Python-Markdown
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
