{% set version = "0.7" %}

package:
  name: python-markdown-math
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-markdown-math/python-markdown-math-{{ version }}.tar.gz
  sha256: 17a12175e8b2052a1c3402fca410841c551c678046293b1f7c280ccfe7b302a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - markdown

test:
  imports:
    - mdx_math

about:
  home: https://github.com/mitya57/python-markdown-math
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Math extension for Python-Markdown.

extra:
  recipe-maintainers:
    - ocefpaf
