travis:
  secure:
    BINSTAR_TOKEN: TTnYbR/rvhUS8BIdUEZQoUvrX9Q38sRrGarUr521MvA0NhoeZw0BLZk5OrC9/mGI9CHBWlGTfPKpYy1/E0ZnyjzxTjsx2JZnH5fGgTOp6rtyHWzEKD4SBwfsboR6GWUR3NFGn95fYWXUJNdiHGbFgt1vRN9WY0Xg2fO/NqxKGpaQ+vr5+z+oQHaPMra5+B0PnGlFxgbLxWbdFnO1rDsd6uErM1k9s2TPIYbcLC799WUkcZ+dKO5EpMGFhIwDFS6RJNxkkTuu81xSOjEqy5WIlQkFKdMa0/l6f1cnuvfCkayMx1YQonUGk45xivdlyBR8CpyQsYu/2DSevC35OTUCZHulUMiZw8qUqymLe6ECmzUTyylCs0R5WrdAgNsMentYbqPrbgrXs9XKjMVdRZg31DtcrntpxHfTG1zOn6qnOMh1YNK6gx2OeSM3NbMSZUA+Xas+K1nSL8E6GyrQXoAfIXY2sGdpKoOUCQZK9Q57CIuH/l9hLZ/XAVvKxbNAnHNcf47uqvUN/SZWjCE2ptkcZViY+jnaZbLhFhIsYsjRUxXq+Rq8nX5fqP0EU+vM9fVsI9SArspWP4pBXQTfRUDIcKZTL1oqitNhfxSFaeT9w6IVHkM+M857yztYNWbaYBmyhtTVzy3VqnLVpKEMBzOm32EV9nmbzUrkLOLCqcpFHoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
